config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  devise_for :users, path_names:  { sign_in: "login", sign_out: "logout" },
                     controllers: {
                                    registrations: "user/registrations"
                                  }


  #===============Api Routes================
  require 'api_constraints'

   namespace :api, defaults: { format: :json } do
       # scope per version of api
       scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

         resources :sessions, :only      => [:create, :destroy]
         match '/login'                  => 'sessions#create', :via => [:options, :post]
         post '/logout/:user_id'         => 'sessions#destroy'

         match '/reset_password'         => 'users#reset_password', :via => [:post]
         match '/users/:id'              => 'users#update', :via => [:options, :put, :post]
        #  get '/matches'                  => 'matches#show'

         resources :users, :only         => [:show, :create, :update]

         resources :dealerships, :only   => [:index, :show] do
           resources :sales_reps, :controller => 'sales_reps', :only => [:index, :show]
           resources :service_reps, :controller => 'service_reps', :only => [:index, :show]
         end

         resources :messages

         resources :conversations do
          resources :messages
         end
     end
   end
   #==========================================

  resources :users, only: [:index, :show, :destroy]
  resources :moderators, :controller => 'moderators'
  resources :sales_reps, :controller => 'sales_reps'
  resources :service_reps, :controller => 'service_reps'
  # devise_for :users
  
  resources :conversations do
   resources :messages
  end

  put 'moderators/:id/edit', to: 'moderators#update'
  put 'sales_reps/:id/edit', to: 'sales_reps#update'
  put 'service_reps/:id/edit', to: 'service_reps#update'

  resources :dealerships
  resources :push_notifications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
 belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
 belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

 has_many :messages, dependent: :destroy

 validates_uniqueness_of :sender_id, :scope => :recipient_id

 # ---This validation takes the sender_id and recipient_id for the conversation and checks whether a
 # ---conversation exists between these two ids because we only want two users to have one conversation
 scope :between, -> (sender_id,recipient_id) do
   where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR
          (conversations.sender_id = ? AND conversations.recipient_id =?)",
          sender_id,recipient_id, recipient_id, sender_id)
 end

 def matched_name(current_user)
   if self.sender_id == current_user.id
     return User.find(self.recipient_id).name
   else
     return User.find(self.sender_id).name
   end
 end

 def matched_id(current_user)
   if self.sender_id == current_user.id
     return self.recipient_id
   else
    return self.sender_id
   end
 end

 def matched_email(current_user)
   if self.sender_id == current_user.id
     return User.find(self.recipient_id).email
   else
    return User.find(self.sender_id).email
   end
 end

 def matched_image(current_user)
   if self.sender_id == current_user.id
     return User.find(self.recipient_id).image.url(:thumb)
   else
    return User.find(self.sender_id).image.url(:thumb)
   end
 end

 def matched_dealership(current_user)
   if self.sender_id == current_user.id
     return User.find(self.recipient_id).dealership ? User.find(self.recipient_id).dealership : nil
   else
    return User.find(self.sender_id).dealership ? User.find(self.sender_id).dealership : nil
   end
 end

 def last_message_date
   self.messages.last.created_at
 end

 def format_last_message_date
   date = self.updated_at
   if date < DateTime.now.days_ago(7)
     return date.in_time_zone('Eastern Time (US & Canada)').strftime("%m/%d/%Y")
   elsif date < DateTime.now.beginning_of_day()
     return date.in_time_zone('Eastern Time (US & Canada)').strftime("%A")
   else
     return date.in_time_zone('Eastern Time (US & Canada)').strftime("%l:%M %P")
   end
 end

 # -- For socket.io rooms
 def unique_id
   ENV['IONIC_APP_ID'] + '.' + self.id.to_s
 end

end

app/controllers/api/v1/conversations_controller.rb
class Api::V1::ConversationsController < Api::ApiController
 load_and_authorize_resource
 before_action :authenticate_with_token!

def index
 @conversations = Conversation.where("sender_id = ? OR recipient_id = ?", current_user.id, current_user.id).order(updated_at: :desc)
end

def create
  if Conversation.between(current_user.id ,params[:recipient_id]).present?
     @conversation = Conversation.between(current_user.id, params[:recipient_id])
  else
     @conversation = Conversation.create!(current_user.id, params[:recipient_id])
     puts @conversation.inspect
  end

  # ---The between method checks to see if a conversation between these 2 users
  # ---exists…only if one does not already exist is the conversation created.

end

private
 def conversation_params
  params.permit(:sender_id, :recipient_id)
 end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @rep = User.find(params[:rep_id])
    @conversations = Conversation.where("sender_id = ? OR recipient_id = ?", @rep.id, @rep.id).order(updated_at: :desc)
  end

  def show
  end

  private
   def conversation_params
    params.permit(:rep_id)
   end
end

app/views/conversations/index.html.erb
<div class="col-sm-12" style="padding:0">
  <h1 class="page-heading">Conversations</h1>

  <div class="row text-right" style="padding: 2rem 0;">
    <%= link_to root_path, :class => "btn btn-warning" do  %>
      <i class="fa fa-chevron-circle-left fa-fw" aria-hidden="true"></i>Dashboard
    <% end %>
  </div>

  <!-- BEGIN BORDERED TABLE PORTLET-->
  <div class="portlet light portlet-fit ">
    <div class="portlet-title" style="border-bottom: 0;margin-bottom: 0;padding-bottom: 0;">
        <div class="caption font-red-sunglo">
            <i class="fa fa-comments font-red-sunglo" style="font-size:20px"></i>
            <span class="caption-subject bold uppercase" style="font-size:20px"> <%= @rep.name.present? ? @rep.name : @rep.email %></span>
            <span class="caption-helper"><%= Dealership.find(@rep.dealership_id).name if @rep.dealership_id.present? %></span>
        </div>
    </div>
    <div class="portlet-body">
        <div class="table-scrollable table-scrollable-borderless" style="overflow: visible !imporant;">
            <table class="table table-striped table-bordered table-hover table-checkable order-column" id="conversations_table">
                <thead>
                    <tr class="uppercase" >
                        <th style=" color: #455A64"> Customer </th>
                        <th style=" color: #455A64"> Date </th>
                        <th style=" color: #455A64" class="text-center"> Actions </th>
                    </tr>
                </thead>
                <tbody>
                  <% @conversations.each  do | convo | %>
                    <tr>
                        <td><%= convo.matched_name(@rep).present? ? convo.matched_name(@rep) : convo.matched_email(@rep) %></td>
                        <td><%= convo.format_last_message_date %></td>
                        <td>
                          <div class="actions" style="text-align:center">
                            <div class="btn-group">
                              <%= link_to link_to 'View', conversation_messages_path(conversation_id: convo.id, rep_id: @rep.id), class: "btn dark btn-outline btn-circle btn-sm" %>
                            </div>
                        </div>
                       </td>
                    </tr>
                  <% end %>
                </tbody>
            </table>
        </div>
    </div>
  </div>
  <!-- END BORDERED TABLE PORTLET-->
</div>