config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  devise_for :users, path_names:  { sign_in: "login", sign_out: "logout" },
                     controllers: {
                                    registrations: "user/registrations"
                                  }


  #===============Api Routes================
  require 'api_constraints'

   namespace :api, defaults: { format: :json } do
       # scope per version of api
       scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

         resources :sessions, :only      => [:create, :destroy]
         match '/login'                  => 'sessions#create', :via => [:options, :post]
         post '/logout/:user_id'         => 'sessions#destroy'

         match '/reset_password'         => 'users#reset_password', :via => [:post]
         match '/users/:id'              => 'users#update', :via => [:options, :put, :post]
        #  get '/matches'                  => 'matches#show'

         resources :users, :only         => [:show, :create, :update]

         resources :dealerships, :only   => [:index, :show] do
           resources :sales_reps, :controller => 'sales_reps', :only => [:index, :show]
           resources :service_reps, :controller => 'service_reps', :only => [:index, :show]
         end

         resources :messages

         resources :conversations do
          resources :messages
         end
     end
   end
   #==========================================

  resources :users, only: [:index, :show, :destroy]
  resources :moderators, :controller => 'moderators'
  resources :sales_reps, :controller => 'sales_reps'
  resources :service_reps, :controller => 'service_reps'
  # devise_for :users
  
  resources :conversations do
   resources :messages
  end

  put 'moderators/:id/edit', to: 'moderators#update'
  put 'sales_reps/:id/edit', to: 'sales_reps#update'
  put 'service_reps/:id/edit', to: 'service_reps#update'

  resources :dealerships
  resources :push_notifications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_admin_dashboard.html.erb
<div class="col-lg-12 ">
  <div class="row">
    <h1 class="page-heading">Admin Dashboard</h1>
  </div>
  <div class="row text-right">
    <%= link_to "Manage Dealerships", dealerships_path, :class => "btn btn-info" %>
    <%= link_to "Push Notifications", push_notifications_path, :class => "btn btn-warning" %>
  </div>

  <div class="row" style="padding: 2rem 0">
    <ul class="nav nav-tabs" role="tablist">
      <li class="nav-item active">
        <a class="nav-link" href="#moderator" role="tab" data-toggle="tab">Moderators</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#sales_rep" role="tab" data-toggle="tab">Sales Reps</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#service_rep" role="tab" data-toggle="tab">Service Reps</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#customer" role="tab" data-toggle="tab">Customers</a>
      </li>

    </ul>

    <!-- Tab panes -->
    <div class="tab-content" style= "background-color: white; border-left: 1px solid #ddd; border-right: 1px solid #ddd; border-bottom: 1px solid #ddd; border-radius: 0rem 0rem .25rem .25rem">
      <div role="tabpanel" class="tab-pane fade in active" id="moderator">
        <%= render "partials/moderators_table" %>
      </div>
      <!-- END MODERATORS -->
      <!-- BEGIN SALES REP -->
      <div role="tabpanel" class="tab-pane fade" id="sales_rep">
        <%= render "partials/sales_reps_table" %>
      </div>
      <!-- END SALES REP -->
      <!-- BEGIN SERVICE REP -->
      <div role="tabpanel" class="tab-pane fade" id="service_rep">
        <%= render "partials/service_reps_table" %>
      </div>
      <!-- END SERVICE REP -->
      <div role="tabpanel" class="tab-pane fade" id="customer">
        <%= render "partials/customers_table" %>
      </div>
      <!-- <div role="tabpanel" class="tab-pane fade" id="references">ccc</div> -->
    </div>
  </div>
</div>

app/views/partials/_customer_dashboard.html.erb
<div class="row">
<h1 class="text-sm-center">Customer Dashboard</h1>
</div>

app/views/partials/_customers_table.html.erb
<div class="col-sm-12" style="padding:0">
  <div class="portlet light portlet-fit ">
      <div class="portlet-body" style="padding-top: 15px;">
          <div class="table-scrollable table-scrollable-borderless" style="overflow: visible !imporant;">
              <table class="table table-striped table-bordered table-hover table-checkable order-column" id="customers_table">
                  <thead>
                      <tr class="uppercase" >
                          <th style=" color: #455A64"> # </th>
                          <th style=" color: #455A64"> Email </th>
                          <th style=" color: #455A64"> Name </th>
                          <th style=" color: #455A64"> Dealership </th>
                          <th style=" color: #455A6A"> Since </th>
                          <!-- <th style=" color: #455A64"> Actions </th> -->
                      </tr>
                  </thead>
                  <tbody>
                    <% @customers.each_with_index  do | customer, index| %>
                      <tr>
                          <td><%=  index+1 %></td>
                          <td><%=  customer.email %></td>
                          <td><%=  customer.name %></td>
                          <td><%=  customer.dealership.name if customer.dealership  %></td>
                          <td><%=  customer.created_at.strftime("%m/%d/%Y at %I:%M%p") %></td>
                      </tr>
                    <% end %>
                  </tbody>
              </table>
          </div>
      </div>
  </div>
</div>

app/views/partials/_index.html.erb
<div class="row">
<h1 class="text-sm-center">Standard Landing Page</h1>
<p>
  Place link to app here maybe... def background image
</p>
</div>

app/views/partials/_moderator_dashboard.html.erb
<div class="col-lg-12">

<div class="row">
  <h1 class="page-heading">Moderator Dashboard</h1>
</div>
<div class="row text-right">
  <%= link_to "Dealership Settings", edit_dealership_path(@dealership), :class => "btn btn-info" %>
</div>


<div class="row" style="padding: 2rem 0">
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item active">
      <a class="nav-link active" href="#customer" role="tab" data-toggle="tab">Customers</a>
    </li>
    <!-- <li class="nav-item">
      <a class="nav-link" href="#customer" role="tab" data-toggle="tab">Customers</a>
    </li> -->
    <!-- <li class="nav-item">
      <a class="nav-link" href="#references" role="tab" data-toggle="tab">references</a>
    </li> -->
  </ul>

  <!-- Tab panes -->
    <div class="tab-content" style= "background-color: white; border-left: 1px solid #ddd; border-right: 1px solid #ddd; border-bottom: 1px solid #ddd; border-radius: 0rem 0rem .25rem .25rem">
      <div role="tabpanel" class="tab-pane fade in active" id="customer">
        <%= render "partials/customers_table" %>
      </div>
    </div>
  </div>
</div>

app/views/partials/_moderators_table.html.erb
<div class="col-sm-12" style="padding:0">
  <!-- BEGIN BORDERED TABLE PORTLET-->
  <div class="portlet light portlet-fit ">
      <!-- <div class="portlet-title">
          <div class="caption" style="width:100%; text-align:center !important;">
              <span class="caption-subject sbold uppercase" style="color: #455A64 !important;">Moderators</span>
          </div>
      </div> -->
      <div class="portlet-body" style="padding-top: 15px;">
          <div class="table-scrollable table-scrollable-borderless" style="overflow: visible !imporant;">
              <table class="table table-striped table-bordered table-hover table-checkable order-column" id="moderators_table">
                  <thead>
                      <tr class="uppercase" >
                          <th style=" color: #455A64"> # </th>
                          <th style=" color: #455A64"> Email </th>
                          <th style=" color: #455A64"> Name </th>
                          <th style=" color: #455A64"> Dealership </th>
                          <th style=" color: #455A6A"> Since </th>
                          <th style=" color: #455A64"> Actions </th>
                      </tr>
                  </thead>
                  <tbody>
                    <% @moderators.each_with_index  do | moderator, index| %>
                      <tr>
                          <td><%=  index+1 %></td>
                          <td><%=  moderator.email %></td>
                          <td><%=  moderator.name %></td>
                          <td><%=  Dealership.with_role(:moderator, moderator).first.name %></td>
                          <td><%=  moderator.created_at.strftime("%m/%d/%Y at %I:%M%p") %></td>
                          <td>
                            <div class="actions" style="text-align:center">
                              <div class="btn-group">
                                  <a class="btn dark btn-outline btn-circle btn-sm" href="javascript:;" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" style="text-decoration: none;"> Actions
                                      <i class="fa fa-angle-down"></i>
                                  </a>
                                  <ul class="dropdown-menu pull-right">
                                    <li>
                                      <%= link_to 'Edit',  edit_moderator_path(moderator) %>
                                      <!-- <%= link_to 'Remove',  moderator, method: :delete, data: {confirm: "Are you sure?"} %> -->
                                    </li>
                                  </ul>
                              </div>
                          </div>
                         </td>
                      </tr>
                    <% end %>
                  </tbody>
              </table>

              <div class="row" style="text-align:center">
                <%= link_to 'Add Moderator', new_moderator_url, :class=>"btn btn-outline btn-sm active btn-blue", :style=>"border-radius: 5px !important; margin-top:10px; font-family: 'Muli', 'Helvetica', 'Arial', 'sans-serif'; text-shadow:none; font-variant:none; width: 92%; margin-top:30px" %>
              </div>
          </div>
      </div>
  </div>
  <!-- END BORDERED TABLE PORTLET-->
</div>

app/views/partials/_sales_reps_table.html.erb
<div class="col-sm-12" style="padding:0">
  <div class="portlet light portlet-fit ">
      <div class="portlet-body" style="padding-top: 15px;">
          <div class="table-scrollable table-scrollable-borderless" style="overflow: visible !imporant;">
              <table class="table table-striped table-bordered table-hover table-checkable order-column" id="sales_rep_table">
                  <thead>
                      <tr class="uppercase" >
                          <th style="color: #455A64"> # </th>
                          <th style="color: #455A64">Image</th>
                          <th style="color: #455A64">Email</th>
                          <th style="color: #455A64">Name</th>
                          <th style="color: #455A64">Dealership</th>
                          <th style="color: #455A64">Actions</th>
                      </tr>
                  </thead>
                  <tbody>
                    <% @sales_reps.each_with_index  do | rep, index| %>
                      <tr>
                          <td><%=  index+1 %></td>
                          <td><%= image_tag rep.image.url(:thumb), style: "max-width:50px" %></td>
                          <td><%= rep.email %></td>
                          <td><%= rep.name %></td>
                          <td><%= Dealership.with_role(:sales_rep, rep).first.name %></td>
                          <td>
                            <div class="actions" style="text-align:center">
                              <div class="btn-group">
                                  <a class="btn dark btn-outline btn-circle btn-sm" href="javascript:;" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" style="text-decoration: none;"> Actions
                                      <i class="fa fa-angle-down"></i>
                                  </a>
                                  <ul class="dropdown-menu pull-right">
                                    <li>
                                      <%= link_to 'Edit',  edit_sales_rep_path(rep) %>
                                      <%= link_to 'Conversations', conversations_path(rep_id: rep.id) %>
                                      <!-- <%= link_to 'Remove',  rep, method: :delete, data: {confirm: "Are you sure?"} %> -->
                                    </li>
                                  </ul>
                              </div>
                          </div>
                         </td>
                      </tr>
                    <% end %>
                  </tbody>
              </table>
              <div class="row" style="text-align:center">
                <%= link_to 'Add Sales Representative', new_sales_rep_url, :class=>"btn btn-outline btn-sm active btn-blue", :style=>"border-radius: 5px !important; margin-top:10px; font-family: 'Muli', 'Helvetica', 'Arial', 'sans-serif'; text-shadow:none; font-variant:none; width: 92%; margin-top:30px" %>
              </div>
          </div>
      </div>
  </div>
</div>

app/views/partials/_service_reps_table.html.erb
<div class="col-sm-12" style="padding:0">
  <div class="portlet light portlet-fit ">
      <div class="portlet-body" style="padding-top: 15px;">
          <div class="table-scrollable table-scrollable-borderless" style="overflow: visible !imporant;">
              <table class="table table-striped table-bordered table-hover table-checkable order-column" id="service_rep_table">
                  <thead>
                      <tr class="uppercase" >
                          <th style="color: #455A64"> # </th>
                          <th style="color: #455A64">Image</th>
                          <th style="color: #455A64">Email</th>
                          <th style="color: #455A64">Name</th>
                          <th style="color: #455A64">Dealership</th>
                          <th style="color: #455A64">Actions</th>
                      </tr>
                  </thead>
                  <tbody>
                    <% @service_reps.each_with_index  do | rep, index| %>
                      <tr>
                          <td><%=  index+1 %></td>
                          <td><%= image_tag rep.image.url(:thumb), style: "max-width:50px" %></td>
                          <td><%= rep.email %></td>
                          <td><%= rep.name %></td>
                          <td><%= Dealership.with_role(:service_rep, rep).first.name %></td>
                          <td>
                            <div class="actions" style="text-align:center">
                              <div class="btn-group">
                                  <a class="btn dark btn-outline btn-circle btn-sm" href="javascript:;" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" style="text-decoration: none;"> Actions
                                      <i class="fa fa-angle-down"></i>
                                  </a>
                                  <ul class="dropdown-menu pull-right">
                                    <li>
                                      <%= link_to 'Edit',  edit_service_rep_path(rep) %>
                                      <%= link_to 'Conversations', conversations_path(rep_id: rep.id) %>
                                      <!-- <%= link_to 'Remove',  rep, method: :delete, data: {confirm: "Are you sure?"} %> -->
                                    </li>
                                  </ul>
                              </div>
                          </div>
                         </td>
                      </tr>
                    <% end %>
                  </tbody>
              </table>
              <div class="row" style="text-align:center">
                <%= link_to 'Add Service Representative', new_service_rep_url, :class=>"btn btn-outline btn-sm active btn-blue", :style=>"border-radius: 5px !important; margin-top:10px; font-family: 'Muli', 'Helvetica', 'Arial', 'sans-serif'; text-shadow:none; font-variant:none; width: 92%; margin-top:30px" %>
              </div>
          </div>
      </div>
  </div>
</div>